seed_everything: 2
trainer:
  gradient_clip_val: 5
  gradient_clip_algorithm: norm
  devices: null
  accelerator: gpu
  strategy: auto
  sync_batchnorm: false
  precision: 32
model:
  arch:
    class_path: models.arch.AlignSpatialNet.AlignSpatialNet
    init_args:
      dim_input: 18
      dim_output: 2
      dim_squeeze: 16
      num_layers: 12
      num_freqs: 129
      dim_hidden: 192
      dim_ffn: 384
      cross_mask: 13
      cfg_cln:
      - -mhsa
      - +mhca
      cfg_mix:
      - +mhca
      output: mix+cln
      activation_checkpointing: false # save GPU memory by activation checkpointing
  channels: [0, 1, 2, 3, 4, 5, 6, 7, 8]
  ref_channel: 0
  stft:
    class_path: models.io.stft.STFT
    init_args:
      n_fft: 256
      n_hop: 128
      win_len: null
      win: hann_window
  stft_clean:
    class_path: models.io.stft.STFT
    init_args:
      n_fft: 256
      n_hop: 128
      win_len: null
      win: hann_window
  norm:
    class_path: models.io.norm.Norm
    init_args:
      mode: utterance
      online: false
  loss:
    class_path: models.io.loss.Loss
    init_args:
      loss_func: models.io.loss.neg_snr
      pit: true
      loss_func_kwargs: {}
  optimizer:
  - Adam
  - lr: 0.001
  lr_scheduler:
  - ExponentialLR
  - gamma: 0.99
  metrics:
  - SNR
  - SDR
  - SI_SDR
  - NB_PESQ
  - WB_PESQ
  - eSTOI
  mchunk: null
  val_metric: loss
  write_examples: 200
  ensemble: null
  compile: false
  exp_name: exp
  reset: null